Repository konveyor/mig-operator, pull requests merged in 2020-12, with the labels that each got.

#504 Test fixes
  .travis.yml
  molecule/default/prepare.yml
  molecule/deploy/migration_v1alpha1_migration_cr.yaml
  molecule/test-local/molecule.yml
  roles/migrationcontroller/defaults/main.yml
Labels: 1.4.0, bug

#506 Update velero CRDS to skip validation <3.11
  roles/migrationcontroller/templates/velero_supporting.yml.j2
Labels: 1.4.0, bug

#510 Add 'singular:' for dvm & dvmp
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_directvolumemigration.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_directvolumemigrationprogress.yaml
Labels: 1.4.0

#519 Create LogReader.md
  docs/usage/LogReader.md
Labels: documentation

#528 Update controller name and role
  roles/migrationcontroller/tasks/main.yml
  roles/migrationcontroller/templates/controller.yml.j2
Labels: 1.4.0, controller-bound

#526 CRD changes to add DIM progress reporting
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_directimagemigrations.yaml
  roles/migrationcontroller/files/migration.openshift.io_directimagemigrations.yaml
Labels: 1.4.0, controller-bound

#529 fix file name in crd task
  roles/migrationcontroller/tasks/main.yml
Labels: 1.4.0, bug

#531 Bug 1907785 - Support configurable rsync transfer image
  deploy/downstream-prep.sh
  deploy/non-olm/latest/operator.yml
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/mig-cluster-config.yml.j2
Labels: 1.4.0, controller-bound

#516 Improve hook documentation
  docs/usage/10.md
Labels: documentation

#532 Add rsync-transfer to related images
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.4.0
