Repository konveyor/mig-operator, pull requests merged in 2020-06, with the labels that each got.

#363 update PR template
  docs/pull_request_template.md
Labels: enhancement

#358 Support restic restart changes in mig-controller
  deploy/olm-catalog/konveyor-operator/latest/migcluster.crd.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migcluster.yaml
  roles/migrationcontroller/templates/mig_host_cluster.yml.j2
Labels: 1.2.1, controller-bound, enhancement

#362 add RBAC perms to migration-controller for oauthaccesstoken
  deploy/olm-catalog/konveyor-operator/v1.2.0/konveyor-operator.v1.2.0.clusterserviceversion.yaml
  roles/migrationcontroller/templates/mig_rbac.yml.j2
Labels: non-admin

#369 pin upstream ansible-operator base image to v0.17.1
  build/Dockerfile
Labels: non-admin

#367 add RBAC for subjectaccessreviews
  deploy/olm-catalog/konveyor-operator/v1.2.0/konveyor-operator.v1.2.0.clusterserviceversion.yaml
  roles/migrationcontroller/templates/mig_rbac.yml.j2
Labels: non-admin

#370 Bug 1844638: Add switch for controlling migration rollback
  README.md
  deploy/non-olm/latest/controller-4.yml
  deploy/non-olm/v1.2.2/controller-4.yml
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/konveyor-operator/v1.2.2/konveyor-operator.v1.2.2.clusterserviceversion.yaml
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller.yml.j2
Labels: 1.2.2, bug, controller-bound

#373 Bug 1845361: Remove quotes around bool value for restart restic switch
  roles/migrationcontroller/templates/mig_host_cluster.yml.j2
Labels: 1.2.2, bug
