Repository konveyor/mig-operator, pull requests merged in 2020-09, with the labels that each got.

#443 Add age printer column to mig* CRDs
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_miganalytic.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migcluster.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_mighook.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migmigration.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migplan.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migstorage.yaml
  deploy/olm-catalog/konveyor-operator/v1.3.0/migration_v1alpha1_miganalytic.yaml
  deploy/olm-catalog/konveyor-operator/v1.3.0/migration_v1alpha1_migcluster.yaml
  deploy/olm-catalog/konveyor-operator/v1.3.0/migration_v1alpha1_mighook.yaml
  deploy/olm-catalog/konveyor-operator/v1.3.0/migration_v1alpha1_migmigration.yaml
  deploy/olm-catalog/konveyor-operator/v1.3.0/migration_v1alpha1_migplan.yaml
  deploy/olm-catalog/konveyor-operator/v1.3.0/migration_v1alpha1_migstorage.yaml
  roles/migrationcontroller/files/migration_v1alpha1_miganalytic.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migcluster.yaml
  roles/migrationcontroller/files/migration_v1alpha1_mighook.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migmigration.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migplan.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migstorage.yaml
Labels: controller-bound

#444 Add metrics doc
  docs/usage/Metrics.md
  docs/usage/screenshots/metrics/monitoring-menu.png
  docs/usage/screenshots/metrics/promql-queries.png
Labels: documentation

#447 Point disconnected doc at files that still exist
  docs/usage/DisconnectedDeployment.md
Labels: 1.3.0

#453 Fixes #454 - Use built image to test PR and other minor fixes
  .travis.yml
  README.md
  molecule/cluster/verify.yml
  molecule/default/asserts.yml
  molecule/deploy/migration_v1alpha1_migration_cr.yaml
  molecule/test-cluster/playbook.yml
  molecule/test-local/converge.yml
  molecule/test-local/molecule.yml
  molecule/test-local/prepare.yml
  roles/migrationcontroller/templates/velero_supporting.yml.j2
Labels: 1.3.0

#450 Fixes #435 - Add customizable velero QPS/Burst with increased default
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/velero.yml.j2
Labels: 1.3.0

#457 Fix 3.7 upgrades
  roles/migrationcontroller/templates/velero.yml.j2
Labels: 1.3.0
