Repository konveyor/mig-operator, pull requests merged in 2020-10, with the labels that each got.

#459 Add playook to release a sprint build upstream
  deploy/sprint-build.yml
  docs/releases.md
Labels: 1.3.1

#467 Update hacking.md with opm instructions
  docs/hacking.md
Labels: documentation

#468 Add instructions to export from bundle to appregistry format
  docs/hacking.md
Labels: documentation

#472 Add table of contents to README.md
  README.md
Labels: documentation

#427 Update Cluster, Plan, Storage CRD to include "refresh" spec field. Move StorageClasses cache to MigPlan.
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migcluster.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migplan.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migstorage.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migcluster.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migplan.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migstorage.yaml
Labels: 1.4.0, controller-bound

#473 Rollback on demand update
  README.md
  deploy/non-olm/latest/controller-4.yml
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migmigration.yaml
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/files/migration_v1alpha1_migmigration.yaml
  roles/migrationcontroller/templates/controller.yml.j2
Labels: controller-bound
