Repository konveyor/mig-operator, pull requests merged in 2020-11, with the labels that each got.

#481 [MIG-119] Add pipeline field to MigMigration Status
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migmigration.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migmigration.yaml
Labels: controller-bound

#488 Remove build requirement for podman
  docs/hacking.md
Labels: documentation

#490 Fix OCP 4.1-4.5 instructions
  docs/hacking.md
Labels: documentation

#484 MIG-284: add DirectVolumeMigrationProgress CR for mig-controller
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_directvolumemigrationprogress.yaml
  molecule/test-local/converge.yml
  roles/migrationcontroller/files/migration_v1alpha1_directvolumemigrationprogress.yaml
  roles/migrationcontroller/tasks/main.yml
Labels: controller-bound

#489 CRD changes for direct image/volume migration integration
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_directvolumemigration.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migcluster.yaml
  deploy/olm-catalog/bundle/manifests/migration_v1alpha1_migplan.yaml
  roles/migrationcontroller/files/migration_v1alpha1_directvolumemigration.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migcluster.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migplan.yaml
Labels: controller-bound

#498 Add node selector if defined in MigrationController CR
  roles/migrationcontroller/templates/velero.yml.j2
Labels: 1.4.0

#502 Update values for 1.4.0
  build/Dockerfile.bundle
  deploy/non-olm/stable
  deploy/non-olm/v1.4.0/controller-3.yml
  deploy/non-olm/v1.4.0/controller-4.yml
  deploy/non-olm/v1.4.0/operator.yml
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/bundle/metadata/annotations.yaml
Labels: 1.4.0

#503 add 1.4.0 to skips
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.4.0
