Repository konveyor/mig-operator, pull requests merged in 2020-08, with the labels that each got.

#403 Add instructions for building the container
  docs/hacking.md
Labels: 1.3.0

#372 remove ao-logs container, should land in OpenSfhit 4.5
  build/Dockerfile
  deploy/non-olm/latest/operator.yml
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.3.0

#396 Analytics
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/konveyor-operator/latest/miganalytic.crd.yaml
  docs/usage/Analytics.md
  docs/usage/README.md
  roles/migrationcontroller/files/migration_v1alpha1_miganalytic.yaml
  roles/migrationcontroller/tasks/main.yml
Labels: 1.3.0, controller-bound, enhancement

#412 Add watch verb on all resources for mig-controller SA
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  roles/migrationcontroller/templates/mig_rbac.yml.j2
Labels: 1.3.0, bug

#415 add missing _fqin parameters
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/velero.yml.j2
Labels: 1.3.0

#414 Remove cluster-admin for mig-operator on OCP3
  deploy/non-olm/latest/operator.yml
Labels: 1.3.0

#409 Fix latest due to operator sdk changes
  build/Dockerfile
  roles/migrationcontroller/tasks/main.yml
  roles/migrationcontroller/templates/migration-controller.yml.j2
Labels: 1.3.0

#408 Clarify this operator migrates containers
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.3.0

#413 Rename crds
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_miganalytic.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migcluster.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_mighook.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migmigration.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migplan.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migstorage.yaml
Labels: 1.3.0

#419 Add updated CRDs with printer columns
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_miganalytic.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migcluster.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_mighook.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migmigration.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migplan.yaml
  deploy/olm-catalog/konveyor-operator/latest/migration_v1alpha1_migstorage.yaml
  roles/migrationcontroller/files/migration_v1alpha1_miganalytic.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migcluster.yaml
  roles/migrationcontroller/files/migration_v1alpha1_mighook.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migmigration.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migplan.yaml
  roles/migrationcontroller/files/migration_v1alpha1_migstorage.yaml
Labels: 1.3.0

#399 downstream mtc rename
  deploy/downstream-prep.sh
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
  docs/pull_request_template.md
Labels: 1.3.0

#420 fix OCP3 permissions and entrypoint
  build/Dockerfile
  build/entrypoint
  deploy/non-olm/latest/operator.yml
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.3.0, bug

#421 use infrastructure resource to get cluster URL
  roles/migrationcontroller/tasks/main.yml
Labels: 1.3.0, bug

#423 Replace migration-plugin with new velero-plugin
  deploy/downstream-prep.sh
  deploy/non-olm/latest/operator.yml
  deploy/olm-catalog/konveyor-operator/latest/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.3.0
