Repository konveyor/mig-operator, pull requests merged in 2021-04, with the labels that each got.

#581 Improve proxy config
  roles/migrationcontroller/tasks/main.yml
Labels: 1.5.0, bug, do not merge

#646 [MIG-593] DOCS: Use MTC to migrate state of the applications
  docs/usage/StateOnlyTransfer.md
  docs/usage/screenshots/state-only/elasticsearch/cluster-source.png
  docs/usage/screenshots/state-only/elasticsearch/kibana-source.png
  docs/usage/screenshots/state-only/elasticsearch/login-target.gif
  docs/usage/screenshots/state-only/elasticsearch/migration.png
  docs/usage/screenshots/state-only/elasticsearch/operator-source.png
  docs/usage/screenshots/state-only/elasticsearch/operator-target.png
  docs/usage/screenshots/state-only/elasticsearch/sample-data.png
  docs/usage/screenshots/state-only/elasticsearch/verify-target.gif
  docs/usage/screenshots/state-only/file-uploader/argocd-deployment.png
  docs/usage/screenshots/state-only/file-uploader/file-uploader-source.png
  docs/usage/screenshots/state-only/file-uploader/file-uploader-target.png
  docs/usage/screenshots/state-only/file-uploader/mode-selection.png
  docs/usage/screenshots/state-only/file-uploader/ns-selection.png
  docs/usage/screenshots/state-only/file-uploader/stage-migration.png
Labels: 1.4.4

#647 [MIG-627] Add configuration for pv resizing usage threshold
  docs/usage/IntelligentPVResizing.md
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.4, controller-bound
