Repository konveyor/mig-operator, pull requests merged in 2021-03, with the labels that each got.

#598 Update MigCluster CRDs to include OperatorVersion status field
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_migclusters.yaml
  roles/migrationcontroller/files/migration.openshift.io_migclusters.yaml
Labels: 1.4.2, controller-bound

#599 Bug 1926128: Add tcp proxy configuration parameters
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.2

#600 Cherry-pick operator version check
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_migclusters.yaml
  roles/migrationcontroller/files/migration.openshift.io_migclusters.yaml
Labels: 1.4.2

#603 Cherry-pick DVM proxy settings
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.2

#554 Bug 1859998: Propagate the disable_image_copy to the mig-controller.
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.2, bug, controller-bound

#612 Crane rename
  README.md
  deploy/build-push-subscribe.sh
  deploy/cut-release.yml
  deploy/downstream-prep.sh
  deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml
  deploy/push-dev-metadata.yml
  deploy/push-release-metadata.yml
  deploy/sprint-build.yml
  docs/cors.md
  docs/hacking.md
  docs/pull_request_template.md
  docs/releases.md
  docs/resources_migrated.md
  mig-operator-bundle.yaml
Labels: 1.4.3, 1.5.0

#613 Add common label to Pods deployed by mig-operator
  roles/migrationcontroller/templates/controller.yml.j2
  roles/migrationcontroller/templates/discovery.yml.j2
  roles/migrationcontroller/templates/log_reader.yml.j2
  roles/migrationcontroller/templates/ui.yml.j2
  roles/migrationcontroller/templates/velero.yml.j2
Labels: 1.4.3

#611 restricting privileges for rsync-anyuid scc
  roles/migrationcontroller/templates/custom-rsync-anyuid.yml.j2
Labels: 1.4.3

#617 Update DVM / DVMP CRDs for retry mechanism
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_directvolumemigrations.yaml
  roles/migrationcontroller/files/migration.openshift.io_directvolumemigrationprogresses.yaml
  roles/migrationcontroller/files/migration.openshift.io_directvolumemigrations.yaml
Labels: 1.4.3, controller-bound

#631 Final set of changes for DVM retry
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_directvolumemigrations.yaml
  roles/migrationcontroller/files/migration.openshift.io_directvolumemigrations.yaml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.3, controller-bound

#632 Cherry-pick DVM final set of CRD changes for DVM retry
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_directvolumemigrations.yaml
  roles/migrationcontroller/files/migration.openshift.io_directvolumemigrations.yaml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.3
