Repository konveyor/mig-operator, pull requests merged in 2021-06, with the labels that each got.

#691 Fix 1.5 channel
  build/Dockerfile.bundle
  deploy/olm-catalog/bundle/metadata/annotations.yaml
Labels: 1.5.0

#693 Reduce requests to reduce scheduling failures
  roles/migrationcontroller/defaults/main.yml
Labels: Future Release

#696 Add usage doc on cached client
  docs/usage/CachedClient.md
Labels: documentation

#695 Add publish github action to replace quay builds
  .github/workflows/publish.yml
Labels: enhancement

#697 Add action to keep metadata up to date
  .github/workflows/publish.yml
  deploy/push-dev-metadata.yml
  deploy/push-release-metadata.yml
  docs/releases.md
Labels: Future Release, enhancement
