Repository konveyor/mig-operator, pull requests merged in 2021-01, with the labels that each got.

#534 Add rsync-transfer to v1.4.0 operator.yml
  deploy/non-olm/v1.4.0/operator.yml
Labels: 1.4.0, bug

#540 Add rsync environment variables to mtc controller
  roles/migrationcontroller/templates/controller.yml.j2
Labels: 1.4.0

#537 Add operator.yml and controller-3.yml to root of image
  build/Dockerfile
Labels: 1.4.0

#543 change variable names for rsync client, transfer pods
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller.yml.j2
Labels: 1.4.0

#563 Add BZ automation to repo
  .github/workflows/bz-pr-action.yml
  .github/workflows/pr-merge.yml
Labels: enhancement

#565 Bug 1917810: Add imagestreamtags to skipped resources when image migration is disabled
  roles/migrationcontroller/tasks/main.yml
Labels: 1.4.0, bug
