Repository konveyor/mig-operator, pull requests merged in 2021-02, with the labels that each got.

#561 Add documentation for resources migrated by MTC
  README.md
  docs/resources_migrated.md
Labels: 1.4.0, documentation

#555 Add migration via API documentation
  README.md
  docs/usage/DirectMigrationExampleAPI.md
  docs/usage/IndirectMigrationExampleAPI.md
Labels: 1.4.0, documentation

#558 Add helper script for iterating on mig-operator
  deploy/build-push-subscribe.sh
Labels: enhancement

#567 Fixes #505 - Correct typos in CORS Docs
  docs/cors.md
Labels: bug, documentation

#560 MTC Api documentation
  docs/usage/MTCAPIDoc.md
  docs/usage/README.md
Labels: 1.4.0, documentation

#570 Fixes #557 - Improves Daemonset Node Selector
  docs/usage/1.md
  roles/migrationcontroller/templates/velero.yml.j2
Labels: 1.4.1, bug, documentation, enhancement

#576 add playbook to cut release
  deploy/cut-release.yml
  docs/releases.md
Labels: 1.4.1, enhancement

#582 add variable to enable/disable intelligent pv resizing
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.2

#573 Update miganalytics CRDs
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_miganalytics.yaml
  roles/migrationcontroller/files/migration.openshift.io_miganalytics.yaml
Labels: 1.4.2, controller-bound, enhancement

#586 Update MigPlan CRDs
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_migplans.yaml
  roles/migrationcontroller/files/migration.openshift.io_migplans.yaml
Labels: 1.4.2

#585 Add global flag for automatic PV resizing
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.4.2

#579 Add proxy env vars to the UI when they are defined
  roles/migrationcontroller/templates/ui.yml.j2
Labels: 1.4.2, enhancement

#589 PV resizing docs
  docs/usage/IntelligentPVResizing.md
  docs/usage/README.md
  docs/usage/screenshots/pv-resize/warning-enabled.png
  docs/usage/screenshots/pv-resize/warning.png
Labels: 1.4.2

#588 Update release-1.4.2
  deploy/non-olm/operator.yml
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v1.4.2.clusterserviceversion.yaml
  molecule/test-local/converge.yml
  roles/migrationcontroller/defaults/main.yml
Labels: 1.4.2

#587 Add 1.4.2 to skips
  deploy/olm-catalog/bundle/manifests/konveyor-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.4.2

#578 Add more version changes to cut-release playbook
  deploy/cut-release.yml
Labels: 1.4.2
