Repository konveyor/mig-operator, pull requests merged in 2021-05, with the labels that each got.

#664 Bug 1934877: Add registry timeout configuration variable
  docs/usage/MigClusterConfiguration.md
  docs/usage/README.md
  roles/migrationcontroller/templates/mig-cluster-config.yml.j2
Labels: 1.5.0, controller-bound

#666 Update DVMP printer columns
  deploy/olm-catalog/bundle/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml
  roles/migrationcontroller/files/migration.openshift.io_directvolumemigrationprogresses.yaml
Labels: 1.5.0, controller-bound

#677 Closes #676 Use mig_operator_version for the version string in OLM
  roles/migrationcontroller/templates/migration-controller.yml.j2
Labels: 1.5.0

#672 CRD updates for Velero 1.6
  deploy/olm-catalog/bundle/manifests/backup.crd.yaml
  deploy/olm-catalog/bundle/manifests/backupstoragelocation.crd.yaml
  deploy/olm-catalog/bundle/manifests/downloadrequest.crd.yaml
  deploy/olm-catalog/bundle/manifests/restore.crd.yaml
  deploy/olm-catalog/bundle/manifests/schedule.crd.yaml
  deploy/olm-catalog/bundle/manifests/volumesnapshotlocation.crd.yaml
  roles/migrationcontroller/templates/velero_supporting.yml.j2
Labels: 1.5.0, controller-bound

#673 Add flag to disable discovery svc event collection
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.5.0

#675 Add flag to enable controller cached client
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/controller_config.yml.j2
Labels: 1.5.0

#682 switch from travis to github action
  .github/workflows/molecule.yml
  .travis.yml
  molecule/cluster/converge.yml
  molecule/cluster/create.yml
  molecule/cluster/molecule.yml
  molecule/default/molecule.yml
  molecule/default/playbook.yml
  molecule/kind/asserts.yml
  molecule/kind/converge.yml
  molecule/kind/molecule.yml
  molecule/kind/prepare.yml
  molecule/kind/verify.yml
  molecule/openshift/asserts.yml
  molecule/openshift/converge.yml
  molecule/openshift/destroy.yml
  molecule/openshift/molecule.yml
  molecule/openshift/prepare.yml
  molecule/openshift/verify.yml
  molecule/test-cluster/molecule.yml
  molecule/test-cluster/playbook.yml
  molecule/test-local/prepare.yml
  molecule/test-local/verify.yml
Labels: 1.4.5

#681 Add 1.4.5 to skips
  deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml
Labels: 1.4.5
