Repository konveyor/mig-operator, pull requests merged in 2022-05, with the labels that each got.

#816 Bug 2048537: Add exposed registry validation path
  docs/usage/MigClusterConfiguration.md
  docs/usage/MigrationControllerConfigQuickView.md
  roles/migrationcontroller/templates/mig-cluster-config.yml.j2
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-medium, lgtm

#818 Add release-v1.7 branch to index
  .github/workflows/publish.yml
Labels: approved, lgtm

#819 Add restic CPU/Memory resources requirements
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm

#821 Add: label "app.kubernetes.io/part-of: openshift-migration" is present on restic and velero pods
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm

#824 cherry-picking velero DPA CR
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm

#820 Bug 2088022: Update merge type for DPA CR
  roles/migrationcontroller/defaults/main.yml
  roles/migrationcontroller/tasks/main.yml
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#817 Bug 2048537: add exposed registry validation path (#816)
  docs/usage/MigClusterConfiguration.md
  docs/usage/MigrationControllerConfigQuickView.md
  roles/migrationcontroller/templates/mig-cluster-config.yml.j2
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-medium, lgtm

#828 Disable OADP image backup management
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm

#827 Disable OADP image backup management
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm

#830 Add MTC override to DPA CR
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm

#829 Add MTC override to DPA CR
  roles/migrationcontroller/templates/velero.yml.j2
Labels: approved, lgtm
